expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    exposer: Ingress
    domain: ai.dev.nuxeo.com
    http: true
    tlsacme: true
    tlsSecretName: ai-tls
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

nuxeo:
  fullnameOverride: preview
  nuxeo:
    podAnnotations:
      preview/scm.ref: ${SCM_REF}
    podLabels:
      branch: "$BRANCH_NAME"
      team: ai
      resource: pod
      usage: preview
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: |-
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-body-size: 0
          nginx.ingress.kubernetes.io/server-snippet: ignore_invalid_headers off;
      labels:
        team: ai
        resource: service
        usage: preview
    image:
      repository: ${DOCKER_REGISTRY}/${ORG}/${APP_NAME}
      tag: ${VERSION}
      pullPolicy: Always
    packages: "nuxeo-jira-ai-${JIRA_AI_VERSION}"
    customParams: |-
      JAVA_OPTS=$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n
      nuxeo.ai.insight.client.enable=true
      nuxeo.ai.insight.client.projectid=jira
      nuxeo.ai.insight.client.target.url=https://nuxeo-ai-dev-dev.apps.prod.nuxeo.io/nuxeo
      nuxeo.ai.insight.client.token=${env:AI_INSIGHT_CLIENT_TOKEN}
      nuxeo.ai.insight.datasource.label=dev
      nuxeo.url=${PREVIEW_URL}/nuxeo
      nuxeo.cors.urls=${PREVIEW_URL} https://nuxeo-ai-dev-dev.apps.prod.nuxeo.io
    customEnvs:
      - name: NUXEO_CLID
        valueFrom:
          secretKeyRef:
            name: instance-clid
            key: instance.clid
      - name: AI_INSIGHT_CLIENT_TOKEN
        valueFrom:
          secretKeyRef:
            name: ai-insight-client-token
            key: text
    persistence:
      enabled: ${PERSISTENCE}
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 5
      timeoutSeconds: 10
    readinessProbe:
      periodSeconds: 20
      initialDelaySeconds: 60
      successThreshold: 1
      timeoutSeconds: 10
      failureThreshold: 5
    resources:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        cpu: 4
        memory: 4Gi
  mongodb:
    deploy: ${PERSISTENCE}
    useStatefulSet: ${PERSISTENCE}
    persistence:
      enabled: ${PERSISTENCE}
    labels:
      branch: "$BRANCH_NAME"
      resource: deployment
      team: ai
      usage: preview
    podLabels:
      branch: "$BRANCH_NAME"
      resource: pod
      team: ai
      usage: preview
    tolerations:
      - key: team
        operator: Equal
        value: ai
        effect: NoSchedule
    nodeSelector:
      team: ai
  elasticsearch:
    deploy: ${PERSISTENCE}
    client:
      tolerations:
        - key: team
          operator: Equal
          value: ai
          effect: NoSchedule
      nodeSelector:
        team: ai
      resources:
        limits:
          cpu: "1"
          memory: "1536Mi"
        requests:
          cpu: "25m"
          memory: "1Gi"
    master:
      persistence:
        enabled: ${PERSISTENCE}
      tolerations:
        - key: team
          operator: Equal
          value: ai
          effect: NoSchedule
      nodeSelector:
        team: ai
      resources:
        limits:
          cpu: "1"
          memory: "1536Mi"
        requests:
          cpu: "25m"
          memory: "1Gi"
    data:
      persistence:
        enabled: ${PERSISTENCE}
      tolerations:
        - key: team
          operator: Equal
          value: ai
          effect: NoSchedule
      nodeSelector:
        team: ai
      resources:
        limits:
          cpu: "1"
          memory: "3Gi"
        requests:
          cpu: "25m"
          memory: "2Gi"
  tolerations:
    - key: team
      operator: Equal
      value: ai
      effect: NoSchedule
  nodeSelector:
    team: ai

# workaround https://github.com/helm/helm/issues/4490: global activation by tag, then custom deactivation by value
tags:
  mongodb: true
  elasticsearch: true

local:
  instance_clid:
