// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tensorflow/core/example/example.proto
// Protobuf Java Version: 4.29.3

package org.tensorflow.example;

public interface ExampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.Example)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.Features features = 1;</code>
   * @return Whether the features field is set.
   */
  boolean hasFeatures();
  /**
   * <code>.tensorflow.Features features = 1;</code>
   * @return The features.
   */
  org.tensorflow.example.Features getFeatures();
  /**
   * <code>.tensorflow.Features features = 1;</code>
   */
  org.tensorflow.example.FeaturesOrBuilder getFeaturesOrBuilder();
}
