<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.nuxeo.ai</groupId>
    <artifactId>nuxeo-ai-addons</artifactId>
    <version>4.0.4-SNAPSHOT</version>
  </parent>

  <artifactId>nuxeo-ai-content-intelligence-package</artifactId>
  <packaging>zip</packaging>
  <name>Nuxeo AI Content Intelligence package</name>

  <dependencies>
    <!-- Base distribution(s) for the MP -->
    <dependency>
      <groupId>org.nuxeo.ecm.distribution</groupId>
      <artifactId>nuxeo-nxr-server</artifactId>
      <type>zip</type>
      <scope>provided</scope>
    </dependency>

    <!-- Additional bundles to be deployed by the MP -->
    <dependency>
      <groupId>org.nuxeo.ai</groupId>
      <artifactId>nuxeo-ai-content-intelligence-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.content.intelligence</groupId>
      <artifactId>nuxeo-content-intelligence-connector-core</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.14</version>
        <executions>
          <execution>
            <id>report-aggregate</id>
            <phase>verify</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.reporting.outputDirectory}/${jacoco.aggregateReportDirectory}</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.nuxeo.build</groupId>
        <artifactId>ant-assembly-maven-plugin</artifactId>
        <configuration>
          <buildFiles>
            <buildFile>${basedir}/src/main/assemble/assembly.xml</buildFile>
          </buildFiles>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
