name: CI for PR
on:
  pull_request:
    branches: [master, master-10.10]

jobs:
  build-and-test:
    uses: ./.github/workflows/build_and_test.yml
    with:
      aws-account: 407995386968
      aws-region: us-east-1
    secrets:
      aws-access-key-id: ${{secrets.AI_CI_ROLE_AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AI_CI_ROLE_AWS_ACCESS_KEY_SECRET}}
      packages-auth-user: ${{secrets.PACKAGES_AUTH_USER}}
      packages-auth-token: ${{secrets.PACKAGES_AUTH_TOKEN}}
      connect-auth-user: ${{secrets.CONNECT_AUTH_USER}}
      connect-auth-token: ${{secrets.CONNECT_AUTH_TOKEN}}