name: CI for PR

permissions:
  contents: read
  checks: write
  pull-requests: write


on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: ['2025']
  push:
    branches: ['2025']

jobs:
  build-and-test:
    uses: ./.github/workflows/build_and_test.yml
    with:
      aws-account: 407995386968
      aws-region: us-east-1
      should-push: ${{ github.event_name == 'push' }}
      preview: ${{ github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'preview') }}
    secrets:
      aws-access-key-id: ${{secrets.AI_CI_ROLE_AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AI_CI_ROLE_AWS_ACCESS_KEY_SECRET}}
      packages-auth-user: ${{secrets.REPOSITORY_MANAGER_USERNAME}}
      packages-auth-token: ${{secrets.REPOSITORY_MANAGER_PASSWORD}}
      connect-auth-user: ${{secrets.CONNECT_USERNAME}}
      connect-auth-token: ${{secrets.CONNECT_PASSWORD}}
      google-creds: ${{secrets.GOOGLE_CREDENTIALS}}
      DOCKER_USERNAME: ${{secrets.REPOSITORY_MANAGER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.REPOSITORY_MANAGER_PASSWORD}}
      NUXEO_CLID: ${{secrets.DEVOPS_CLID}}
