name: Release Publish

on:
  pull_request:
    branches: [master, master-10.10]
    inputs:
      increment:
        type: choice
        description: Bug is for patch and feature for minor
        default: 'bug'
        options:
        - 'bug'
        - 'feature'
        - 'major'
      jdk:
        type: choice
        default: '11'
        description: JDK Version
        options:
        - '8'
        - '11'

jobs:
  release-publish:
    name: 'Release & Publish'
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xms1g -Xmx1536m"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK

      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven

    - name: 'Update settings.xml with server configuration'
      run: |
        echo '<settings>
            <servers>
              <server>
                <id>maven-internal</id>
                <username>${{secrets.PACKAGES_AUTH_USER}}</username>
                <password>${{secrets.PACKAGES_AUTH_TOKEN}}</password>
              </server>
              <server>
                <id>maven-team-platform-private</id>
                <username>${{secrets.PACKAGES_AUTH_USER}}</username>
                <password>${{secrets.PACKAGES_AUTH_TOKEN}}</password>
              </server>
              <server>
                <id>maven-private</id>
                <username>${{secrets.PACKAGES_AUTH_USER}}</username>
                <password>${{secrets.PACKAGES_AUTH_TOKEN}}</password>
              </server>
              <server>
                <id>maven-public-releases</id>
                <username>${{secrets.PACKAGES_AUTH_USER}}</username>
                <password>${{secrets.PACKAGES_AUTH_TOKEN}}</password>
              </server>
              <server>
                <id>nuxeo-studio</id>
                <username>${{secrets.CONNECT_AUTH_USER}}</username>
                <password>${{secrets.CONNECT_AUTH_TOKEN}}</password>
              </server>
            </servers>
            </settings>' > ~/.m2/settings.xml
    - name: Set env
      run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
      id: project
    - name: Tag and check if compiling
      run: |
        currentVersion=${{ steps.project.outputs.version }}
        releasedVersion=${currentVersion%-*}
        echo "RELEASED_VERSION=${releasedVersion}" >> $GITHUB_ENV
        find ./ -type f -exec sed -i '' -e "s/${currentVersion}/${releasedVersion}/" {} \;
        git clean -f -d
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b release-v${releasedVersion}
        git add .
        git status
        git tag -a v${releasedVersion} -m "Release ${releasedVersion}"
        mvn -ntp install -DskipTests
        git push origin v${releasedVersion}
        git push origin release-v${releasedVersion}

    - name: Archive packages
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: |
          nuxeo-ai-core-package/target/nuxeo-ai-*.zip
          addons/nuxeo-ai-*-package/target/nuxeo-ai-*.zip

    - name: Publish Nuxeo packages
      env:
        CONNECT_PREPROD_URL: https://nos-preprod-connect.nuxeocloud.com/nuxeo
      run: |
        PACKAGE="nuxeo-ai-core-package/target/nuxeo-ai-core-$RELEASED_VERSION.zip"
        STATUS_CODE=`curl -i --silent --output publish-req.output -w "%{http_code}" -u "${{ secrets.CONNECT_PREPROD_AUTH }}" -F package=@$PACKAGE "$CONNECT_PREPROD_URL/site/marketplace/upload?batch=true"`
        cat publish-req.output
        if [[ "$STATUS_CODE" != "200" ]]
        then
          exit 1
        else
          exit 0
        fi

    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: $CURRENT_VERSION
        version-fragment: 'bug'

    - name: Post Release (in master or master-10.10)
      run: |
        git checkout ${{ github.base_ref }}
        find ./ -type f -exec sed -i '' -e "s/$CURRENT_VERSION/${{ steps.bump_version.outputs.next-version }}/" {} \;
        git clean -f -d
        git add .
        git commit -m "Post Release $CURRENT_VERSION"
        git push origin ${{ github.base_ref }}
