name: CI for PR
on:
  pull_request:
    branches: [master, master-10.10, release-*, '2023']
  push:
    branches: [master, master-10.10, '2023']

jobs:
  build-and-test:
    uses: ./.github/workflows/build_and_test.yml
    with:
      aws-account: 407995386968
      aws-region: us-east-1
      should-push: ${{ github.event_name == 'push' }}
    secrets:
      aws-access-key-id: ${{secrets.AI_CI_ROLE_AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AI_CI_ROLE_AWS_ACCESS_KEY_SECRET}}
      packages-auth-user: ${{secrets.PACKAGES_AUTH_USER}}
      packages-auth-token: ${{secrets.PACKAGES_AUTH_TOKEN}}
      connect-auth-user: ${{secrets.CONNECT_AUTH_USER}}
      connect-auth-token: ${{secrets.CONNECT_AUTH_TOKEN}}
  notify-on-error:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ failure() && github.event_name == 'push' }}
    steps:
      - name: Slack Notification
        id: slack
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          channel-id: "C9W4P9RKM"
          slack-message: "Nuxeo AI Core ${{ github.workflow }} workflow failed!\n${{ github.event.head_commit.url }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATION_BOT_TOKEN }}
