name: Release Publish

on:
  workflow_dispatch:
    inputs:
      increment:
        type: version
        description: Bug is for patch and feature for minor
        options:
        - bug
        - feature
        - major

jobs:
  release-publish-10.10:
    name: 'Release Publish Master 10.10'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master-10.10'
    env:
      MAVEN_OPTS: "-Xms1g -Xmx1536m"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven

    - name: 'Update settings.xml with server configuration'
      run: |
        echo '<settings>
            <servers>
              <server>
                <id>maven-internal</id>
                <username>${{ secrets.packages-auth-user }}</username>
                <password>${{ secrets.packages-auth-token }}</password>
              </server>
              <server>
                <id>maven-private</id>
                <username>${{ secrets.packages-auth-user }}</username>
                <password>${{ secrets.packages-auth-token }}</password>
              </server>
              <server>
                <id>nuxeo-studio</id>
                <username>${{ secrets.connect-auth-user }}</username>
                <password>${{ secrets.connect-auth-token }}</password>
              </server>
            </servers>
            </settings>' > ~/.m2/settings.xml

    - name: Set env
      run: echo "CURRENT_VERSION=\"$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)\"" >> $GITHUB_ENV
    - name: Tag and check if compiling
      run: |
        currentVersionSnap=$CURRENT_VERSION
        currentVersion=${currentVersionSnap%-*}
        find ./ -type f -exec sed -i '' -e "s/${currentVersionSnap}/${currentVersion}/" {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b release-v${currentVersion}
        git tag -a v${currentVersion} -m "Release ${currentVersion}"
        mvn -ntp install -DskipInstall
        git push origin v${currentVersion}
        git push origin release-v${currentVersion}

    - name: Archive packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: |
          nuxeo-ai-core-package/target/nuxeo-ai-core-${{ github.event.inputs.version }}.zip

    - name: Publish Nuxeo packages
      env:
        CONNECT_PREPROD_URL: https://nos-preprod-connect.nuxeocloud.com/nuxeo
      run: |
        PACKAGE="nuxeo-ai-core-package/target/nuxeo-ai-core-${{ github.event.inputs.version }}.zip"
        STATUS_CODE=`curl -i --silent --output publish-req.output -w "%{http_code}" -u "${{ secrets.CONNECT_PREPROD_AUTH }}" -F package=@$PACKAGE "$CONNECT_PREPROD_URL/site/marketplace/upload?batch=true"`
        cat publish-req.output
        if [[ "$STATUS_CODE" != "200" ]]
        then
          exit 1
        else
          exit 0
        fi

    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ github.event.inputs.version }}
        version-fragment: ${{ github.event.inputs.increment }}

    - name: Post Release
      run: |
        git checkout ${{ github.ref }}
        find ./ -type f -exec sed -i '' -e "s/${{ github.event.inputs.version }}-SNAPSHOT/${{ steps.bump_version.outputs.next-version }}-SNAPSHOT/" {} \;
        git add .
        git commit -m "Post Release ${{ github.event.inputs.version }}"
        git push ${{ github.ref }}

  release-publish-lts:
    name: 'Release Publish Master LTS 2021'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      MAVEN_OPTS: "-Xms1g -Xmx1536m"
    outputs:
      version: ${{ steps.project.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven

    - name: 'Update settings.xml with server configuration'
      run: |
        echo '<settings>
            <servers>
              <server>
                <id>maven-internal</id>
                <username>${{ secrets.packages-auth-user }}</username>
                <password>${{ secrets.packages-auth-token }}</password>
              </server>
              <server>
                <id>maven-private</id>
                <username>${{ secrets.packages-auth-user }}</username>
                <password>${{ secrets.packages-auth-token }}</password>
              </server>
              <server>
                <id>nuxeo-studio</id>
                <username>${{ secrets.connect-auth-user }}</username>
                <password>${{ secrets.connect-auth-token }}</password>
              </server>
            </servers>
            </settings>' > ~/.m2/settings.xml

    - name: Set env
      run: echo "CURRENT_VERSION=\"$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)\"" >> $GITHUB_ENV
    - name: Tag and check if compiling
      run: |
        currentVersionSnap=$CURRENT_VERSION
        currentVersion=${currentVersionSnap%-*}
        find ./ -type f -exec sed -i '' -e "s/${currentVersionSnap}/${currentVersion}/" {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b release-v${currentVersion}
        git tag -a v${currentVersion} -m "Release ${currentVersion}"
        mvn -ntp install -DskipInstall
        git push origin v${currentVersion}
        git push origin release-v${currentVersion}

    - name: Archive packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: |
          nuxeo-ai-core-package/target/nuxeo-ai-core-${{ github.event.inputs.version }}.zip

    - name: Publish Nuxeo packages
      env:
        CONNECT_PREPROD_URL: https://nos-preprod-connect.nuxeocloud.com/nuxeo
      run: |
        PACKAGE="nuxeo-ai-core-package/target/nuxeo-ai-core-${{ github.event.inputs.version }}.zip"
        STATUS_CODE=`curl -i --silent --output publish-req.output -w "%{http_code}" -u "${{ secrets.CONNECT_PREPROD_AUTH }}" -F package=@$PACKAGE "$CONNECT_PREPROD_URL/site/marketplace/upload?batch=true"`
        cat publish-req.output
        if [[ "$STATUS_CODE" != "200" ]]
        then
          exit 1
        else
          exit 0
        fi

    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ github.event.inputs.version }}
        version-fragment: ${{ github.event.inputs.increment }}

    - name: Post Release
      run: |
        git checkout ${{ github.ref }}
        find ./ -type f -exec sed -i '' -e "s/${{ github.event.inputs.version }}-SNAPSHOT/${{ steps.bump_version.outputs.next-version }}-SNAPSHOT/" {} \;
        git add .
        git commit -m "Post Release ${{ github.event.inputs.version }}"
        git push ${{ github.ref }}